{% set name = "pyzxing" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyzxing-{{ version }}.tar.gz
  sha256: ac9efa22fce567e3f4234cd6392a1aa2e01fef6ec62753e57cf9038a9c64a231

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib
    - numpy
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - pyzxing
    - src
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ChenjieXu/pyzxing
  summary: Python wrapper for ZXing Java library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChenjieXu
